#pragma once
#include "CoreMinimal.h"
#include "EChatCommentType.generated.h"

UENUM(BlueprintType)
enum class EChatCommentType : uint8 {
    Good,
    Noisy,
    GreatSkill,
    Impressed,
    ReallyGreat,
    Strong,
    Nice,
    AsExpected,
    Oops,
    Chance,
    Regrettable,
    DoYourBest,
    DoingGreat,
    GoodGame,
    NiceFight,
    NiceToMeetYou,
    ThankYouForWaiting,
    ThankYou,
    ThankYouForHardWork,
    LetsPlayAgain,
    GoodMorning,
    Hello,
    GoodEvening,
    ByeBye,
    GoodBye,
    ItWasFun,
    ItWasGoodGame,
    ExcuseMe,
    ThankYouForContinousBattle,
    Participate,
    PlayNextTime,
    RevengeSameCharacter,
    LetMeRevenge,
    PlayMainCharacter,
    DeliverIt,
    RegisterFriend,
    StartIt,
    WaitAnotherPlayer,
    IsItOK,
    IsOK,
    IsPlayAgain,
    IsItAboutToDissolve,
    EnterThe1stOfP1,
    EnterThe2ndOfP1,
    EnterThe3rdOfP1,
    EnterThe1stOfP2,
    EnterThe2ndOfP2,
    EnterThe3rdOfP2,
    IsReplaceTeamMembers,
    OK,
    NotOK,
    Sorry,
    NoProblem,
    DontWorry,
    ItsOkay,
    OnlyOne,
    PleaseWait,
    Yes,
    No,
};

