#pragma once
#include "CoreMinimal.h"
#include "EGameMode.generated.h"

UENUM(BlueprintType)
enum class EGameMode : uint8 {
    GAME_MODE_VERSUS,
    GAME_MODE_STORY,
    GAME_MODE_TUTORIAL,
    GAME_MODE_TRAINING,
    GAME_MODE_REPLAY,
    GAME_MODE_TESTBATTLE,
    GAME_MODE_DEMO_TEST,
    GAME_MODE_DEMO_TEST_FUTURE,
    GAME_MODE_NONE,
    GAME_MODE_QUEUE2PLAY,
    GAME_MODE_TRIAL,
    GAME_MODE_TOURNAMENT,
    GAME_MODE_RANKEDMATCH,
    GAME_MODE_RANKEDMATCH_CPU,
    GAME_MODE_CASUALMATCH,
    GAME_MODE_ROOMMATCH,
    GAME_MODE_ROOMMATCH_PARTY,
    GAME_MODE_ROOMMATCH_DRAFT,
    GAME_MODE_ONLINE_TRAINING,
    GAME_MODE_ROOMMATCH_PARTY_OFFLINE_CHECK_MODE,
    GAME_MODE_BOSS,
    MAX,
};

