#pragma once
#include "CoreMinimal.h"
#include "EOrangeMenuID.generated.h"

UENUM(BlueprintType)
enum class EOrangeMenuID : uint8 {
    Versus,
    Story,
    Traning,
    RankMatch,
    CasualMatch,
    RoomMatch,
    OnlineTraning,
    Replay,
    Profile,
    LeaderBoard,
    DJStation,
    Tutorial,
    Mission,
    Gallery,
    Option,
    PlayerData,
    Store,
    OnlineReplay,
    SaveReplay,
    PersonalReplay,
    LB_RankedMatch,
    LB_Story,
    LB_BossChallenge,
    LB_CloneBattle,
    LB_ModeEnd,
    BasicAction,
    AttackBehavior,
    Trial,
    BossChallenge,
    Movie,
    Artwork,
    Voice,
    LanguageSetting,
    SystemSetting,
    GameSetting,
    SoundSetting,
    DisplaySetting,
    GraphicsSetting,
    ButtonConfig,
    BattleSetting,
    None,
};

