#pragma once
#include "CoreMinimal.h"
#include "ETitleState.generated.h"

UENUM(BlueprintType)
enum class ETitleState : uint8 {
    EXECUTE_WAIT,
    EXECUTE_SAVE_MESSAGE,
    EXECUTE_NOTE_MESSAGE,
    EXECUTE_WARNING_MESSAGE,
    EXECUTE_HEALTH_MESSAGE,
    EXECUTE_SNK_LOGO,
    EXECUTE_UE_LOGO,
    EXECUTE_WWISE_LOGO,
    EXECUTE_INTRAGAMES_LOGO,
    EXECUTE_GAMEPOCH_LOGO,
    EXECUTE_OPENING_MOVIE,
    EXECUTE_TITLE_LOGO,
    EXECUTE_BUTTON_LOOP_EFFECT,
    FINISH_TITLE,
    NETWORK_CHECK,
    NETWORK_CHECK_OK,
    AGREEMENT,
    TERMS_OF_SERVICES,
    PRIVACY_POLICY,
    GOTO_MAIN_MENU,
    END = 0x13,
    MAX,
};

